# Generated by Django 5.2 on 2025-04-30 10:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_otp_expires_at_alter_otp_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(default=accounts.models.default_expiration),
        ),
    ]
